# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectReport(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 766)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 766))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 766))
        MainWindow.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(-30, 750, 1421, 16))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_9.setLineWidth(10)
        self.line_9.setMidLineWidth(0)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, -10, 16, 791))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setLineWidth(10)
        self.line_6.setMidLineWidth(0)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(1080, 190, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"\n"
"")
        self.label_69.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1220, 50, 81, 31))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"color: rgb(0, 0, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#pushButton_3:hover{\n"
"padding-left:5px;\n"
"border:1px solid black;\n"
"}\n"
"#pushButton_3:pressed{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(50, 44, 101, 40))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("\n"
"color: rgb(255, 0, 0);\n"
"\n"
"\n"
"")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_72 = QtWidgets.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(1020, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"\n"
"")
        self.label_72.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(-30, 0, 1451, 16))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setLineWidth(10)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(1350, -10, 20, 821))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_7.setLineWidth(10)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(150, 44, 131, 40))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"\n"
"")
        self.label_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 130, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"background-color: rgb(255, 255, 255);border: 1px solid black;\n"
"\n"
"border-radius: 10px;\n"
"}\n"
"#lineEdit:hover{\n"
"border: 1px solid black;\n"
"}\n"
"#lineEdit:focus{\n"
"border: 1px solid red;\n"
"}\n"
"\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(420, 130, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox.setStyleSheet("#comboBox{\n"
"    background-color: rgb(220, 220, 220);border: 1px solid black;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(420, 190, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox_8.setStyleSheet("#comboBox_8{\n"
"    background-color: rgb(220, 220, 220);border: 1px solid black;\n"
"\n"
"color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"}")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(720, 190, 201, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox_3.setStyleSheet("#comboBox_3{\n"
"    background-color: rgb(220, 220, 220);border: 1px solid black;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(510, 190, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(980, 190, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"color: rgb(255, 255, 255);border: 1px solid black;\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:15px;\n"
"}\n"
"#pushButton_4:hover{\n"
"border:2px solid white;\n"
"padding-bottom: 3px;\n"
"padding-right: 3px;\n"
"}\n"
"#pushButton_4:pressed{\n"
"border:none;\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget_2.setGeometry(QtCore.QRect(700, 380, 321, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calendarWidget_2.setFont(font)
        self.calendarWidget_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calendarWidget_2.setStyleSheet("#calendarWidget_2 QWidget {\n"
"    alternate-background-color: #B8E2FF;\n"
"}\n"
"#qt_calendar_navigationbar {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #B8E2FF;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth {\n"
"    border: none;\n"
"    qproperty-icon: none;\n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    margin-left: 3px;\n"
"    image: url(:/newPrefix/back-arrow.png);\n"
"}\n"
"#qt_calendar_nextmonth {\n"
"    border: none;\n"
"    qproperty-icon: none;\n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    margin-right: 3px;\n"
"    image: url(:/newPrefix/redo-arrow.png);\n"
"}\n"
"#qt_calendar_prevmonth:hover, #qt_calendar_nextmonth:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"#qt_calendar_prevmonth:pressed, #qt_calendar_nextmonth:pressed {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#qt_calendar_yearbutton {\n"
"    color: rgb(0, 0, 0);\n"
"    margin: 5px;\n"
"    border-radius: 5px;\n"
"    font-size: 13px;\n"
"    padding: 0 10px;\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"#qt_calendar_monthbutton {\n"
"    width: 110px;\n"
"    background-color: rgb(255, 255, 127);\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 13px;\n"
"    padding: 0 2px;\n"
"    margin: 5px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"#qt_calendar_yearbutton:hover, #qt_calendar_monthbutton:hover {\n"
"    background-color: rgb(250, 255, 190);\n"
"}\n"
"#qt_calendar_yearbutton:pressed, #qt_calendar_monthbutton:pressed {\n"
"    background-color: #B8E2FF;\n"
"}\n"
"#qt_calendar_yearedit {\n"
"    min-width: 60px;\n"
"    color: rgb(0, 0, 0);\n"
"    background: transparent;\n"
"    font-size: 13px;\n"
"}\n"
"#qt_calendar_yearedit::down-button {\n"
"    subcontrol-position: left;\n"
"    image: url(:/newPrefix/arrow.png);\n"
"}\n"
"#qt_calendar_yearedit::up-button {\n"
"    subcontrol-position: right;\n"
"    image: url(:/newPrefix/arrow-up.png);\n"
"}\n"
"#qt_calendar_yearedit::down-button, #qt_calendar_yearedit::up-button {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    padding: 0px 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"#qt_calendar_yearedit::down-button:hover, #qt_calendar_yearedit::up-button:hover {\n"
"    background-color: #B8E2FF;\n"
"}\n"
"#qt_calendar_yearedit::down-button:pressed, #qt_calendar_yearedit::up-button:pressed {\n"
"    background-color: #fff;\n"
"}\n"
"#calendarWidget_2 QToolButton QMenu {\n"
"    background-color: #fff;\n"
"}\n"
"#calendarWidget_2 QToolButton QMenu::item {\n"
"    /*padding:5px;*/\n"
"}\n"
"#calendarWidget_2 QToolButton QMenu::item:selected:enabled {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#calendarWidget_2 QToolButton::menu-indicator {\n"
"    nosubcontrol-origin: margin;\n"
"    subcontrol-position: right center;\n"
"    margin-top: 10px; \n"
"    width: 20px;\n"
"}\n"
"\n"
"#qt_calendar_calendarview {\n"
"    border: 2px solid #B8E2FF;\n"
"    border-top: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"#qt_calendar_calendarview::item:hover {\n"
"    background-color: #aaffff;\n"
"    border-radius: 5px;\n"
"}\n"
"#qt_calendar_calendarview::item:selected {\n"
"    background-color: #55aaff;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.calendarWidget_2.setGridVisible(False)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 130, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 190, 71, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("#pushButton_12{\n"
"color: rgb(0, 0, 255);border: 1px solid black;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#pushButton_12:hover{\n"
"padding-left:5px;\n"
"border:1px solid black;\n"
"}\n"
"#pushButton_12:pressed{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_12.setCheckable(False)
        self.pushButton_12.setAutoExclusive(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(720, 130, 201, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_4.setStyleSheet("#comboBox_4{\n"
"    background-color: rgb(220, 220, 220);border: 1px solid black;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(640, 176, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton.setObjectName("radioButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 190, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("#lineEdit_2{\n"
"background-color: rgb(255, 255, 255);border: 1px solid black;\n"
"\n"
"border-radius: 10px;\n"
"}\n"
"#lineEdit_2:hover{\n"
"border: 1px solid black;\n"
"}\n"
"#lineEdit_2:focus{\n"
"border: 1px solid red;\n"
"}\n"
"")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(330, 380, 321, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarWidget.setMouseTracking(False)
        self.calendarWidget.setTabletTracking(False)
        self.calendarWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calendarWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.calendarWidget.setStyleSheet("#calendarWidget QWidget {\n"
"    alternate-background-color: #B8E2FF;\n"
"}\n"
"#qt_calendar_navigationbar {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #B8E2FF;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth {\n"
"    border: none;\n"
"    qproperty-icon: none;\n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    margin-left: 3px;\n"
"    image: url(:/newPrefix/back-arrow.png);\n"
"}\n"
"#qt_calendar_nextmonth {\n"
"    border: none;\n"
"    qproperty-icon: none;\n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    margin-right: 3px;\n"
"    image: url(:/newPrefix/redo-arrow.png);\n"
"}\n"
"#qt_calendar_prevmonth:hover, #qt_calendar_nextmonth:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"#qt_calendar_prevmonth:pressed, #qt_calendar_nextmonth:pressed {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#qt_calendar_yearbutton{\n"
"\n"
"color: rgb(0, 0, 0);\n"
"margin: 5px;\n"
"border-radius: 5px;\n"
"font-size: 13px;\n"
"padding: 0 10px;\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"#qt_calendar_monthbutton{\n"
"width:110px;\n"
"    background-color: rgb(255, 255, 127);\n"
"    color: rgb(0, 0, 0);\n"
"font-size: 13px;\n"
"padding: 0 2px;\n"
"margin: 5px 0;\n"
"border-radius: 5px;\n"
"}\n"
"#qt_calendar_yearbutton:hover, #qt_calendar_monthbutton:hover{\n"
"background-color: rgb(250, 255, 190);\n"
"}\n"
"#qt_calendar_yearbutton:pressed, #qt_calendar_monthbutton:pressed{\n"
"background-color: #B8E2FF;\n"
"}\n"
"#qt_calendar_yearedit{\n"
"min-width:60px;\n"
"    color: rgb(0, 0, 0);\n"
"background: transparent;\n"
"font-size: 13px;\n"
"}\n"
"#qt_calendar_yearedit::down-button{\n"
"subcontrol-position: left;\n"
"    image: url(:/newPrefix/arrow.png);\n"
"}\n"
"#qt_calendar_yearedit::up-button{\n"
"subcontrol-position: right;\n"
"    image: url(:/newPrefix/arrow-up.png);\n"
"}\n"
"#qt_calendar_yearedit::down-button, #qt_calendar_yearedit::up-button{\n"
"width: 18px;\n"
"height: 18px;\n"
"padding: 0px 5px;\n"
"border-radius:3px;\n"
"}\n"
"#qt_calendar_yearedit::down-button:hover, #qt_calendar_yearedit::up-button:hover{\n"
"background-color: #B8E2FF;\n"
"}\n"
"#qt_calendar_yearedit::down-button:pressed, #qt_calendar_yearedit::up-button:pressed{\n"
"background-color: #fff;\n"
"}\n"
"#calendarWidget QToolButton QMenu {\n"
"background-color: #fff;\n"
"}\n"
"#calendarWidget QToolButton QMenu::item{\n"
"/*padding:5px;*/\n"
"}\n"
"#calendarWidget QToolButton QMenu::item:selected:enabled{\n"
"background-color: #55aaff;\n"
"}\n"
"\n"
"#calendarWidget QToolButton::menu-indicator{\n"
"nosubcontrol-origin: margin;\n"
"subcontrol-position: right center;\n"
"margin-top: 10px; \n"
"width: 20px;\n"
"}\n"
"\n"
"#qt_calendar_calendarview{\n"
"border: 2px solid #B8E2FF;\n"
"border-top: 0px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"#qt_calendar_calendarview::item:hover{\n"
"background-color: #aaffff;\n"
"border-radius: 5px;\n"
"\n"
"}\n"
"#qt_calendar_calendarview::item:selected{\n"
"background-color: #55aaff;\n"
"border-radius: 5px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(370, 190, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 130, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(540, 130, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox_2.setStyleSheet("#comboBox_2{\n"
"    background-color: rgb(220, 220, 220);border: 1px solid black;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 130, 71, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"color: rgb(0, 0, 255);border: 1px solid black;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#pushButton_8:hover{\n"
"padding-left:5px;\n"
"border:1px solid black;\n"
"}\n"
"#pushButton_8:pressed{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setAutoExclusive(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(540, 190, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox_7.setStyleSheet("#comboBox_7{\n"
"    background-color: rgb(220, 220, 220);border: 1px solid black;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"}")
        self.comboBox_7.setObjectName("comboBox_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1050, 130, 251, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 180, 0);\n"
"border-radius: 15px;\n"
"}\n"
"#pushButton_5:hover{\n"
"border:2px solid white;\n"
"padding-bottom: 3px;\n"
"padding-right: 3px;\n"
"}\n"
"#pushButton_5:pressed{\n"
"border:none;\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(980, 130, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(640, 120, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_2.setObjectName("radioButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 250, 1271, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setStyleSheet("#tableWidget{\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid white;\n"
"    alternate-background-color: rgb(232, 232, 232);\n"
"}\n"
"QHeaderView{\n"
"\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(203, 237, 255);\n"
"}\n"
"QTableWidget::item:hover{\n"
"background-color: rgb(208, 208, 208);}")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(3)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(20)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 19, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(1320, 31, 20, 701))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(28, 31, 20, 701))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(40, 90, 1289, 16))
        self.line_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_17.setLineWidth(3)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setObjectName("line_17")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(600, 100, 20, 139))
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(3)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setObjectName("line_10")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(40, 230, 1289, 20))
        self.line_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_18.setLineWidth(3)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setObjectName("line_18")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(40, 24, 1289, 16))
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setLineWidth(3)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(330, 100, 20, 139))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(40, 720, 1289, 20))
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setLineWidth(3)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(940, 100, 20, 139))
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(3)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setObjectName("line_11")
        self.line_6.raise_()
        self.label_69.raise_()
        self.pushButton_3.raise_()
        self.label_34.raise_()
        self.label_72.raise_()
        self.line_7.raise_()
        self.label_49.raise_()
        self.lineEdit.raise_()
        self.comboBox.raise_()
        self.comboBox_8.raise_()
        self.comboBox_3.raise_()
        self.label_12.raise_()
        self.pushButton_4.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.pushButton_12.raise_()
        self.comboBox_4.raise_()
        self.radioButton.raise_()
        self.lineEdit_2.raise_()
        self.label_11.raise_()
        self.label_6.raise_()
        self.comboBox_2.raise_()
        self.pushButton_8.raise_()
        self.comboBox_7.raise_()
        self.pushButton_5.raise_()
        self.checkBox.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.radioButton_2.raise_()
        self.tableWidget.raise_()
        self.calendarWidget.raise_()
        self.calendarWidget_2.raise_()
        self.line_5.raise_()
        self.line_3.raise_()
        self.line_17.raise_()
        self.line_18.raise_()
        self.line_16.raise_()
        self.line_4.raise_()
        self.line_15.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_69.setText(_translate("MainWindow", "Oops : Something Went Wrong..."))
        self.pushButton_3.setText(_translate("MainWindow", "Return"))
        self.label_34.setText(_translate("MainWindow", "Select"))
        self.label_72.setText(_translate("MainWindow", "24 June 2024 12 : 34 : 56"))
        self.label_49.setText(_translate("MainWindow", "Reports"))
        self.lineEdit.setText(_translate("MainWindow", "2020-10-14"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "--- All Jobs ---"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "JobName 1"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "JobName 2"))
        self.label_12.setText(_translate("MainWindow", "MI:"))
        self.pushButton_4.setText(_translate("MainWindow", "Search"))
        self.label_4.setText(_translate("MainWindow", "TO:"))
        self.label_3.setText(_translate("MainWindow", "FROM:"))
        self.label_5.setText(_translate("MainWindow", "HH:"))
        self.pushButton_12.setText(_translate("MainWindow", "DATE"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "-- All Batch Ids ---"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "COMPRESSION"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "TEAR"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "FLXURAL"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "ILSS"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "QLSS"))
        self.radioButton.setText(_translate("MainWindow", "Job :"))
        self.lineEdit_2.setText(_translate("MainWindow", "2020-10-14"))
        self.label_11.setText(_translate("MainWindow", "HH:"))
        self.label_6.setText(_translate("MainWindow", "MI:"))
        self.pushButton_8.setText(_translate("MainWindow", "DATE"))
        self.pushButton_5.setText(_translate("MainWindow", "View All Reports PDF"))
        self.checkBox.setText(_translate("MainWindow", "ALL"))
        self.radioButton_2.setText(_translate("MainWindow", "Batch :"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Test ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Specimen ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Job Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Batch ID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "product ID "))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Part No."))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Current"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Client"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Serial No."))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Output Power"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Rotational Direction"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Starter Capacitor"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Operation Capacitor"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Phase"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Voltage"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Pole"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Motor Speed"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Frequency"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Test Condition"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "001"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "100"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "67"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "45"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow", "67"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("MainWindow", "34"))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("MainWindow", "45"))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("MainWindow", "78"))
        item = self.tableWidget.item(0, 13)
        item.setText(_translate("MainWindow", "56"))
        item = self.tableWidget.item(0, 14)
        item.setText(_translate("MainWindow", "56"))
        item = self.tableWidget.item(0, 15)
        item.setText(_translate("MainWindow", "43"))
        item = self.tableWidget.item(0, 16)
        item.setText(_translate("MainWindow", "76"))
        item = self.tableWidget.item(0, 17)
        item.setText(_translate("MainWindow", "89"))
        item = self.tableWidget.item(0, 18)
        item.setText(_translate("MainWindow", "90"))
        item = self.tableWidget.item(0, 19)
        item.setText(_translate("MainWindow", "45"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SelectReport()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
