# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fci_45_pendings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from fci_46_status_recipt_pop import fci_46_Ui_MainWindow
from fci_47_status_issue_pop import fci_47_Ui_MainWindow
from fci_48_status_other_pop import fci_48_Ui_MainWindow
from fci_49_status_ALL_pop import fci_49_Ui_MainWindow

import datetime
import sqlite3

class fci_45_Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 768)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(47, 141, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 1311, 701))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.frame.setFont(font)
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        
        
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(1030, 10, 260, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(60)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 600, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 600, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 180, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(510, 600, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(650, 200, 20, 611))
        self.line.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(150, 110, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(810, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(370, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(90, 90, 134);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        
        self.pushButton_8_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_1.setGeometry(QtCore.QRect(600, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8_1.setFont(font)
        self.pushButton_8_1.setStyleSheet("background-color: rgb(90, 90, 134);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8_1.setObjectName("pushButton_8_1")
        
        
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 250, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setGeometry(QtCore.QRect(370, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgb(90, 90, 134);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 180, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(150, 180, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox.setObjectName("comboBox")
        
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(370, 180, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(420, 180, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_2.setObjectName("comboBox_2")
       
        self.comboBox_7 = QtWidgets.QComboBox(self.frame)
        self.comboBox_7.setGeometry(QtCore.QRect(420, 320, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_7.setObjectName("comboBox_7")
        
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(40, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(370, 320, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.comboBox_8 = QtWidgets.QComboBox(self.frame)
        self.comboBox_8.setGeometry(QtCore.QRect(150, 320, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_8.setObjectName("comboBox_8")
       
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 390, 661, 20))
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setObjectName("line_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(40, 600, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(90, 90, 134);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(0, 560, 661, 20))
        self.line_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(-7, 400, 20, 291))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(180, 400, 20, 301))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(330, 400, 20, 301))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(3)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(480, 400, 20, 301))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(3)
        self.line_7.setObjectName("line_7")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(50, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(220, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(370, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(530, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(0, 450, 661, 20))
        self.line_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(3)
        self.line_8.setObjectName("line_8")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(40, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(200, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(350, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(500, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget.setGeometry(QtCore.QRect(600, 150, 341, 231))
        self.calendarWidget.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget_2.setGeometry(QtCore.QRect(960, 310, 341, 231))
        self.calendarWidget_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.calendarWidget_2.setGridVisible(True)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        
        self.calendarWidget_3 = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget_3.setGeometry(QtCore.QRect(100, 150, 341, 231))
        self.calendarWidget_3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.calendarWidget_3.setGridVisible(True)
        self.calendarWidget_3.setObjectName("calendarWidget_3")
        
        self.calendarWidget_4 = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget_4.setGeometry(QtCore.QRect(260, 310, 341, 231))
        self.calendarWidget_4.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.calendarWidget_4.setGridVisible(True)
        self.calendarWidget_4.setObjectName("calendarWidget_4")
        
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(730, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(1060, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(90, 90, 134);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(840, 110, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(1060, 310, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(1060, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color: rgb(90, 90, 134);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.comboBox_9 = QtWidgets.QComboBox(self.frame)
        self.comboBox_9.setGeometry(QtCore.QRect(1110, 310, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_9.setObjectName("comboBox_9")
        
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(730, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(840, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox_10 = QtWidgets.QComboBox(self.frame)
        self.comboBox_10.setGeometry(QtCore.QRect(840, 310, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_10.setObjectName("comboBox_10")
        
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(730, 240, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(1110, 170, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_3.setObjectName("comboBox_3")
       
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(1060, 170, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(730, 170, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(840, 170, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_4.setObjectName("comboBox_4")
        
        self.line_9 = QtWidgets.QFrame(self.frame)
        self.line_9.setGeometry(QtCore.QRect(1137, 400, 20, 301))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(3)
        self.line_9.setObjectName("line_9")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(1007, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(1157, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(857, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setGeometry(QtCore.QRect(657, 450, 661, 20))
        self.line_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(3)
        self.line_10.setObjectName("line_10")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(697, 420, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setGeometry(QtCore.QRect(657, 390, 661, 20))
        self.line_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(3)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.frame)
        self.line_12.setGeometry(QtCore.QRect(987, 400, 20, 301))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(3)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.frame)
        self.line_13.setGeometry(QtCore.QRect(650, 400, 20, 301))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(3)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.frame)
        self.line_14.setGeometry(QtCore.QRect(810, 400, 20, 291))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(3)
        self.line_14.setObjectName("line_14")
        self.label_53 = QtWidgets.QLabel(self.frame)
        self.label_53.setGeometry(QtCore.QRect(890, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.frame)
        self.label_54.setGeometry(QtCore.QRect(720, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame)
        self.label_55.setGeometry(QtCore.QRect(1040, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame)
        self.label_56.setGeometry(QtCore.QRect(1200, 490, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame)
        self.pushButton_23.setGeometry(QtCore.QRect(1020, 600, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 180, 0);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame)
        self.pushButton_24.setGeometry(QtCore.QRect(700, 600, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("background-color: rgb(90, 90, 134);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame)
        self.pushButton_25.setGeometry(QtCore.QRect(870, 600, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.frame)
        self.pushButton_26.setGeometry(QtCore.QRect(1180, 600, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.pushButton_26.setObjectName("pushButton_26")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 21))
        self.menubar.setObjectName("menubar")
        
        self.line_1_1 = QtWidgets.QFrame(self.frame)
        self.line_1_1.setGeometry(QtCore.QRect(648, 30, 20, 60))
        self.line_1_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line_1_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1_1.setLineWidth(3)
        self.line_1_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_1_1.setObjectName("line")
        
        
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.from_dt=""
        self.to_dt=""
        self.from_dt2=""
        self.to_dt2=""
        self.pending_all_cnt=0
        self.pending_recipt_cnt=0
        self.pending_issue_cnt=0
        self.pending_other_cnt=0
        
        self.completed_all_cnt=0
        self.completed_recipt_cnt=0
        self.completed_issue_cnt=0
        self.completed_other_cnt=0
        self.device_location_type=""

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "05 Aug 2020 12:45:00"))
        self.pushButton_3.setText(_translate("MainWindow", "LIST"))
        self.pushButton_4.setText(_translate("MainWindow", "LIST"))
        self.pushButton_5.setText(_translate("MainWindow", "LIST"))
        self.lineEdit.setText(_translate("MainWindow", "2020-10-14"))
        self.pushButton_9.setText(_translate("MainWindow", "PENDING"))
        self.pushButton_10.setText(_translate("MainWindow", "COMPLETED"))
        self.label_3.setText(_translate("MainWindow", "FROM:"))
        self.pushButton_8.setText(_translate("MainWindow", "DATE"))
        self.pushButton_8_1.setText(_translate("MainWindow", " RETURN "))
        self.label_4.setText(_translate("MainWindow", "TO:"))
        self.lineEdit_2.setText(_translate("MainWindow", "2020-10-14"))
        self.pushButton_12.setText(_translate("MainWindow", "DATE"))
        self.label_5.setText(_translate("MainWindow", "HH:"))
        
        self.i=0        
        for x in range(24):            
            self.comboBox.addItem("")
            self.comboBox.setItemText(self.i,str("%02d"%x))
            #print("i :"+str(x))
            self.i=self.i+1
       
        self.label_6.setText(_translate("MainWindow", "MI:"))
        
        self.i=0        
        for x in range(60):            
            self.comboBox_2.addItem("")
            self.comboBox_2.setItemText(self.i,str("%02d"%x))
            #print("i :"+str(x))
            self.i=self.i+1
        
        self.i=0        
        for x in range(60):            
            self.comboBox_7.addItem("")
            self.comboBox_7.setItemText(self.i,str("%02d"%x))
            #print("i :"+str(x))
            self.i=self.i+1
        self.label_11.setText(_translate("MainWindow", "HH:"))
        self.label_12.setText(_translate("MainWindow", "MI:"))
        
        self.i=0        
        for x in range(24):            
            self.comboBox_8.addItem("")
            self.comboBox_8.setItemText(self.i,str("%02d"%x))
            #print("i :"+str(x))
            self.i=self.i+1
            
            
        self.pushButton_13.setText(_translate("MainWindow", "LIST"))
       
       
        self.label_21.setText(_translate("MainWindow", "100"))
        self.label_22.setText(_translate("MainWindow", "50"))
        self.label_23.setText(_translate("MainWindow", "30"))
        self.label_24.setText(_translate("MainWindow", "20"))
        self.label_25.setText(_translate("MainWindow", "ALL"))
        self.label_26.setText(_translate("MainWindow", "BUY"))
        self.label_27.setText(_translate("MainWindow", "SELL"))
        self.label_28.setText(_translate("MainWindow", "WEIGHING"))
        self.label_7.setText(_translate("MainWindow", "FROM:"))
        self.pushButton_11.setText(_translate("MainWindow", "DATE"))
        self.lineEdit_3.setText(_translate("MainWindow", "2020-10-14"))
        self.label_13.setText(_translate("MainWindow", "MI:"))
        
        self.pushButton_14.setText(_translate("MainWindow", "DATE"))
        
        self.i=0        
        for x in range(60):            
            self.comboBox_9.addItem("")
            self.comboBox_9.setItemText(self.i,str("%02d"%x))
            #print("i :"+str(x))
            self.i=self.i+1
       
        
        self.label_14.setText(_translate("MainWindow", "HH:"))
        self.lineEdit_4.setText(_translate("MainWindow", "2020-10-14"))
        self.i=0        
        for x in range(24):            
            self.comboBox_10.addItem("")
            self.comboBox_10.setItemText(self.i,str("%02d"%x))
            #print("i :"+str(x))
            self.i=self.i+1
        
        self.label_8.setText(_translate("MainWindow", "TO:"))
        self.i=0        
        for x in range(60):            
            self.comboBox_3.addItem("")
            self.comboBox_3.setItemText(self.i,str("%02d"%x))           
            self.i=self.i+1
        
        self.label_9.setText(_translate("MainWindow", "MI:"))
        self.label_10.setText(_translate("MainWindow", "HH:"))
        self.i=0        
        for x in range(24):            
            self.comboBox_4.addItem("")
            self.comboBox_4.setItemText(self.i,str("%02d"%x))           
            self.i=self.i+1
        self.label_29.setText(_translate("MainWindow", "SELL"))
        self.label_30.setText(_translate("MainWindow", "WEIGHING"))
        self.label_31.setText(_translate("MainWindow", "BUY"))
        self.label_32.setText(_translate("MainWindow", "ALL"))
        self.label_53.setText(_translate("MainWindow", "50"))
        self.label_54.setText(_translate("MainWindow", "100"))
        self.label_55.setText(_translate("MainWindow", "30"))
        self.label_56.setText(_translate("MainWindow", "20"))
        self.pushButton_23.setText(_translate("MainWindow", "LIST")) #issue
        self.pushButton_24.setText(_translate("MainWindow", "LIST")) #all
        self.pushButton_25.setText(_translate("MainWindow", "LIST")) #recipt
        self.pushButton_26.setText(_translate("MainWindow", "LIST")) #other
        self.comboBox.setCurrentText("00")
        self.comboBox.setCurrentText("00")
        self.comboBox_8.setCurrentText("23")
        self.comboBox_7.setCurrentText("59")
        
        self.comboBox_3.setCurrentText("00")
        self.comboBox_4.setCurrentText("00")
        self.comboBox_10.setCurrentText("23")
        self.comboBox_9.setCurrentText("59")
        
        self.lineEdit.setText(datetime.datetime.now().strftime("%Y-%m-%d"))
        self.lineEdit_2.setText(datetime.datetime.now().strftime("%Y-%m-%d"))
        
        self.lineEdit_3.setText(datetime.datetime.now().strftime("%Y-%m-%d"))
        self.lineEdit_4.setText(datetime.datetime.now().strftime("%Y-%m-%d"))
        
        self.pushButton_8_1.clicked.connect(MainWindow.close)
        self.calendarWidget.hide()
        self.calendarWidget_2.hide()
        self.calendarWidget_3.hide()
        self.calendarWidget_4.hide()
        self.pushButton_9.clicked.connect(self.load_pending)
        self.pushButton_10.clicked.connect(self.load_completed)
        
        self.pushButton_3.clicked.connect(self.open_new_window2)
        self.pushButton_4.clicked.connect(self.open_new_window3)
        self.pushButton_5.clicked.connect(self.open_new_window4)
        self.pushButton_13.clicked.connect(self.open_new_window5)
        
        self.pushButton_26.clicked.connect(self.open_new_window4) #other
        self.pushButton_25.clicked.connect(self.open_new_window2) #recipt
        self.pushButton_24.clicked.connect(self.open_new_window5) #all
        self.pushButton_23.clicked.connect(self.open_new_window3) #issue
        
        #self.load_data()
        
        self.pushButton_8.clicked.connect(self.from_on_click1)
        self.pushButton_12.clicked.connect(self.to_on_click2)
        
        self.pushButton_11.clicked.connect(self.from2_on_click1)
        self.pushButton_14.clicked.connect(self.to2_on_click2)
       
        self.calendarWidget.clicked.connect(self.calendar1_on_click)
        self.calendarWidget_2.clicked.connect(self.calendar2_on_click)
        self.calendarWidget_3.clicked.connect(self.calendar3_on_click)
        self.calendarWidget_4.clicked.connect(self.calendar4_on_click)
        self.load_pending()
        
        self.comboBox.currentTextChanged.connect(self.load_pending)
        self.comboBox.currentTextChanged.connect(self.load_pending)
        self.comboBox_8.currentTextChanged.connect(self.load_pending)
        self.comboBox_7.currentTextChanged.connect(self.load_pending)
        
        self.timer1=QtCore.QTimer()
        self.timer1.setInterval(1000)        
        self.timer1.timeout.connect(self.device_date)
        self.timer1.start(1)
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT DEVICE_LOCATION_TYPE FROM GLOBAL_VAR") 
        for x in results:            
            self.device_location_type=str(x[0])           
        connection.close()
        
        if(self.device_location_type=="SITE"):
                    self.pushButton_4.setDisabled(True)
                    self.pushButton_23.setDisabled(True)
                    
            
            
    
    
    def device_date(self):     
        self.label_20.setText(datetime.datetime.now().strftime("%d %b %Y %H:%M:%S"))
        
    def from_on_click1(self):
        self.calendarWidget.show()
    
    def to_on_click2(self):
        self.calendarWidget_2.show()
        
    def calendar1_on_click(self):
        temp_var = self.calendarWidget.selectedDate() 
        var_name = temp_var.toPyDate()        
        self.from_dt=str(var_name)
        self.lineEdit.setText(str(self.calendarWidget.selectedDate().toString(QtCore.Qt.ISODate)))
        self.calendarWidget.hide()
        self.load_pending()
    
    def calendar2_on_click(self):
        temp_var = self.calendarWidget_2.selectedDate() 
        var_name = temp_var.toPyDate()        
        self.to_dt=str(var_name)
        self.lineEdit_2.setText(str(self.calendarWidget_2.selectedDate().toString(QtCore.Qt.ISODate)))
        self.calendarWidget_2.hide()
        self.load_pending()
        
        
    def from2_on_click1(self):
        self.calendarWidget_3.show()
    
    def to2_on_click2(self):
        self.calendarWidget_4.show()
        
    def calendar3_on_click(self):
        temp_var = self.calendarWidget_3.selectedDate() 
        var_name = temp_var.toPyDate()        
        self.from_dt2=str(var_name)
        self.lineEdit_3.setText(str(self.calendarWidget_3.selectedDate().toString(QtCore.Qt.ISODate)))
        self.calendarWidget_3.hide()
        self.load_completed()
    
    def calendar4_on_click(self):
        temp_var = self.calendarWidget_4.selectedDate() 
        var_name = temp_var.toPyDate()        
        self.to_dt2=str(var_name)
        self.lineEdit_4.setText(str(self.calendarWidget_4.selectedDate().toString(QtCore.Qt.ISODate)))
        self.calendarWidget_4.hide()
        self.load_completed()
        
        
    def load_data(self):        
        
        self.from_dt=self.lineEdit.text()+" "+str(self.comboBox.currentText())+":"+str(self.comboBox_2.currentText())+":00"
        self.to_dt=self.lineEdit_2.text()+" "+str(self.comboBox_8.currentText())+":"+str(self.comboBox_7.currentText())+":00"
        
        self.from_dt2=self.lineEdit_3.text()+" "+str(self.comboBox_3.currentText())+":"+str(self.comboBox_4.currentText())+":00"
        self.to_dt2=self.lineEdit_4.text()+" "+str(self.comboBox_10.currentText())+":"+str(self.comboBox_9.currentText())+":00"
        
        
 
        


    def load_pending(self):
        self.pending_show()
        self.completed_hide()
        self.load_data()
        connection = sqlite3.connect("fci.db")
        with connection:        
            cursor = connection.cursor()
            cursor.execute("UPDATE GLOBAL_VAR SET STATUS = 'PENDING', STATUS_FROM='"+str(self.from_dt)+"', STATUS_TO='"+str(self.to_dt)+"'")
        connection.commit();
        connection.close()
        self.pending_all_cnt=0
        self.pending_recipt_cnt=0
        self.pending_issue_cnt=0
        self.pending_other_cnt=0
        
        #print("SELECT COUNT(*) FROM WEIGHT_MST WHERE BATCH_ID IS  NULL AND ISSUE_ID IS NOT NULL AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt)+"' and '"+str(self.to_dt)+"' ") 
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='FIRST' AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt)+"' and '"+str(self.to_dt)+"' ") 
        for x in results:
            self.pending_all_cnt=str(x[0])
        connection.close()
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='FIRST' AND BATCH_ISSUE_FLG='BUY'  AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt)+"' and '"+str(self.to_dt)+"' ") 
        for x in results:
            self.pending_recipt_cnt=str(x[0])
        connection.close()
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='FIRST' AND BATCH_ISSUE_FLG='SELL'  AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt)+"' and '"+str(self.to_dt)+"' ") 
        for x in results:
            self.pending_issue_cnt=str(x[0])
        connection.close()
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='FIRST' AND  BATCH_ISSUE_FLG='WEIGHING'  AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt)+"' and '"+str(self.to_dt)+"' ") 
        for x in results:
            self.pending_other_cnt=str(x[0])
        connection.close()
        
        
        self.label_21.setText(str(self.pending_all_cnt))
        self.label_22.setText(str(self.pending_recipt_cnt))
        self.label_23.setText(str(self.pending_issue_cnt))
        self.label_24.setText(str(self.pending_other_cnt))
        
    def load_completed(self):
        self.completed_show()
        self.pending_hide()
        self.load_data()
        connection = sqlite3.connect("fci.db")
        with connection:        
            cursor = connection.cursor()
            cursor.execute("UPDATE GLOBAL_VAR SET STATUS = 'COMPLETED', STATUS_FROM='"+str(self.from_dt2)+"', STATUS_TO='"+str(self.to_dt2)+"'")
        connection.commit();
        connection.close()
        
        self.completed_all_cnt=0
        self.completed_recipt_cnt=0
        self.completed_issue_cnt=0
        self.completed_other_cnt=0
        
        #print("SELECT COUNT(*) FROM WEIGHT_MST WHERE BATCH_ID IS  NULL AND ISSUE_ID IS NOT NULL AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt)+"' and '"+str(self.to_dt)+"' ") 
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='SECOND' AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt2)+"' and '"+str(self.to_dt2)+"' ") 
        for x in results:
            self.completed_all_cnt=str(x[0])
        connection.close()
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='SECOND' AND BATCH_ISSUE_FLG='BUY' AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt2)+"' and '"+str(self.to_dt2)+"' ") 
        for x in results:
            self.completed_recipt_cnt=str(x[0])
        connection.close()
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='SECOND' AND  BATCH_ISSUE_FLG='SELL' AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt2)+"' and '"+str(self.to_dt2)+"' ") 
        for x in results:
            self.completed_issue_cnt=str(x[0])
        connection.close()
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT COUNT(*) FROM WEIGHT_MST WHERE STATUS='SECOND' AND  BATCH_ISSUE_FLG='WEIGHING'  AND FIRST_WT_CRTEATED_ON between '"+str(self.from_dt2)+"' and '"+str(self.to_dt2)+"' ") 
        for x in results:
            self.completed_other_cnt=str(x[0])
        connection.close()
        
        
        self.label_54.setText(str(self.completed_all_cnt))
        self.label_53.setText(str(self.completed_recipt_cnt))
        self.label_55.setText(str(self.completed_issue_cnt))
        self.label_56.setText(str(self.completed_other_cnt))
        
       

    def pending_hide(self):
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.lineEdit.hide()
        self.label_3.hide()
        self.pushButton_8.hide()
        self.label_4.hide()
        self.lineEdit_2.hide()
        self.pushButton_12.hide()
        self.pushButton_13.hide()
        self.comboBox.hide()
        self.label_6.hide()
        self.comboBox_2.hide()
        self.label_5.hide()
        
        self.label_11.hide()
        self.label_12.hide()
        self.comboBox_7.hide()
        self.comboBox_8.hide()
        
        self.label_21.hide()
        self.label_22.hide()
        self.label_23.hide()
        self.label_24.hide()
        
        self.label_25.hide()
        self.label_26.hide()
        self.label_27.hide()
        self.label_28.hide()
        
        
        #self.line.hide()
        self.line_2.hide()
        self.line_3.hide()
        self.line_4.hide()
        
        self.line_5.hide()
        self.line_6.hide()
        self.line_7.hide()
        self.line_8.hide()
       
        
        
    def pending_show(self):
        self.pushButton_3.show()
        self.pushButton_4.show()
        self.pushButton_5.show()
        self.lineEdit.show()
        self.label_3.show()
        self.pushButton_8.show()
        self.label_4.show()
        self.lineEdit_2.show()
        self.pushButton_12.show()
        self.pushButton_13.show()
        self.comboBox.show()
        self.label_6.show()
        self.comboBox_2.show()
        self.label_5.show()
        
        self.label_11.show()
        self.label_12.show()
        self.comboBox_7.show()
        self.comboBox_8.show()
        
        self.label_21.show()
        self.label_22.show()
        self.label_23.show()
        self.label_24.show()
        
        self.label_25.show()
        self.label_26.show()
        self.label_27.show()
        self.label_28.show()
        
        
        #self.line.show()
        self.line_2.show()
        self.line_3.show()
        self.line_4.show()
        
        self.line_5.show()
        self.line_6.show()
        self.line_7.show()
        self.line_8.show()
       
    
    def completed_hide(self):
        self.pushButton_14.hide()
        self.comboBox_9.hide()
        self.comboBox_10.hide()
        self.comboBox_3.hide()
        self.comboBox_4.hide()
        self.label_14.hide()
        self.lineEdit_4.hide()
        self.label_29.hide()
        self.label_30.hide()
        self.label_31.hide()
        self.label_32.hide()
        self.label_53.hide()
        self.label_54.hide()
        self.label_55.hide()
        self.label_56.hide()
        self.pushButton_23.hide()
        self.pushButton_24.hide()
        self.pushButton_25.hide()
        self.pushButton_26.hide()
        
        self.pushButton_11.hide()
        self.lineEdit_3.hide()
        self.label_13.hide()
        
        self.label_7.hide()
        self.label_8.hide()
        self.label_9.hide()
        self.label_10.hide()
        
        self.line_9.hide()
        self.line_10.hide()
        self.line_11.hide()
        
        self.line_12.hide()
        self.line_13.hide()
        self.line_14.hide()
        
        
    def completed_show(self):
        self.pushButton_14.show()
        self.comboBox_9.show()
        self.comboBox_10.show()
        self.comboBox_3.show()
        self.comboBox_4.show()
        self.label_14.show()
        self.lineEdit_4.show()
        self.label_29.show()
        self.label_30.show()
        self.label_31.show()
        self.label_32.show()
        self.label_53.show()
        self.label_54.show()
        self.label_55.show()
        self.label_56.show()
        self.pushButton_23.show()
        self.pushButton_24.show()
        self.pushButton_25.show()
        self.pushButton_26.show()
        
        self.pushButton_11.show()
        self.lineEdit_3.show()
        self.label_13.show()
        
        self.label_7.show()
        self.label_8.show()
        self.label_9.show()
        self.label_10.show()
        
        self.line_9.show()
        self.line_10.show()
        self.line_11.show()
        
        self.line_12.show()
        self.line_13.show()
        self.line_14.show()
        
    def open_new_window2(self):       
        self.window = QtWidgets.QMainWindow()
        self.ui=fci_46_Ui_MainWindow()
        self.ui.setupUi(self.window)           
        self.window.show()
        
    def open_new_window3(self):       
        self.window = QtWidgets.QMainWindow()
        self.ui=fci_47_Ui_MainWindow()
        self.ui.setupUi(self.window)           
        self.window.show()
        
    def open_new_window4(self):       
        self.window = QtWidgets.QMainWindow()
        self.ui=fci_48_Ui_MainWindow()
        self.ui.setupUi(self.window)           
        self.window.show()
        
    def open_new_window5(self):       
        self.window = QtWidgets.QMainWindow()
        self.ui=fci_49_Ui_MainWindow()
        self.ui.setupUi(self.window)           
        self.window.show()
    
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = fci_45_Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
