# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fci_24_update_delete_record.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMenu, QVBoxLayout, QSizePolicy, QMessageBox, QWidget, QPushButton

import sqlite3
import re
import datetime
import time

class fci_25_Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 768)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(221, 255, 234);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 1311, 711))
        '''
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        '''
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(1130, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(440, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(780, 650, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_3.setGeometry(QtCore.QRect(460, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setGeometry(QtCore.QRect(460, 50, 331, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 40, 171, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(0, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setGeometry(QtCore.QRect(920, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_7.setEnabled(False)
        self.groupBox_7.setGeometry(QtCore.QRect(920, 60, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox.setGeometry(QtCore.QRect(60, 30, 101, 31))
        self.comboBox.setObjectName("comboBox")        
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(1160, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(30, 170, 1251, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 60, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 30, 141, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(920, 650, 351, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(20, 240, 241, 441))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.listWidget.setFont(font)        
        self.listWidget.setObjectName("listWidget")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(730, 210, 511, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(20, 40, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_6.setGeometry(QtCore.QRect(150, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("background-color: rgb(221, 255, 234) ; color: rgb(0, 0, 0);")
        self.comboBox_6.setObjectName("comboBox_6")
       
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(30, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(280, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setGeometry(QtCore.QRect(30, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(150, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(10, 190, 481, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_7.setGeometry(QtCore.QRect(160, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setStyleSheet("background-color: rgb(221, 255, 234) ; color: rgb(0, 0, 0);")
        self.comboBox_7.setObjectName("comboBox_7")
        
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(160, 270, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(30, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_11.setGeometry(QtCore.QRect(160, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_38 = QtWidgets.QLabel(self.groupBox)
        self.label_38.setGeometry(QtCore.QRect(30, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setGeometry(QtCore.QRect(290, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(30, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(400, 270, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(293, 180, 20, 511))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(320, 200, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(330, 250, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(330, 300, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(330, 350, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(310, 400, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(320, 470, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(310, 530, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(440, 250, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(440, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(440, 301, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(221, 255, 234) ; color: rgb(0, 0, 0);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(440, 350, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(221, 255, 234) ; color: rgb(0, 0, 0);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(440, 410, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(440, 470, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color: rgb(221, 255, 234) ; color: rgb(0, 0, 0);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame)
        self.comboBox_5.setGeometry(QtCore.QRect(440, 530, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("background-color: rgb(221, 255, 234) ; color: rgb(0, 0, 0);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_41 = QtWidgets.QLabel(self.frame)
        self.label_41.setGeometry(QtCore.QRect(310, 590, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame)
        self.label_42.setGeometry(QtCore.QRect(450, 590, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame)
        self.label_43.setGeometry(QtCore.QRect(730, 600, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame)
        self.label_44.setGeometry(QtCore.QRect(840, 600, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame)
        self.label_45.setGeometry(QtCore.QRect(930, 600, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame)
        self.label_46.setGeometry(QtCore.QRect(1030, 600, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(610, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(30, 190, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.login_user_id=""
        self.login_user_role=""
        self.net_wt=0

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "05 Aug 2020 12:45:00 "))
        self.pushButton_7.setText(_translate("MainWindow", "Save"))
        self.pushButton_8.setText(_translate("MainWindow", "Return"))
        self.radioButton_3.setText(_translate("MainWindow", "Vehicle No."))
        self.groupBox_5.setTitle(_translate("MainWindow", "."))
        self.label_22.setText(_translate("MainWindow", "Vehicle No: "))
        self.radioButton_4.setText(_translate("MainWindow", " Batch only"))
        self.comboBox.setItemText(0, _translate("MainWindow", "45"))
        self.comboBox.setItemText(1, _translate("MainWindow", "46"))
        self.pushButton_9.setText(_translate("MainWindow", "Search "))
        self.radioButton_5.setText(_translate("MainWindow", "Serial No."))
        self.label_23.setText(_translate("MainWindow", "Serial. No.:"))
        self.label_24.setText(_translate("MainWindow", "Message: "))
        self.groupBox.setTitle(_translate("MainWindow", "Weights"))
        self.label_33.setText(_translate("MainWindow", "First Wt. Mode:"))
        
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")        
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Tare"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Gross"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "None"))
        self.label_34.setText(_translate("MainWindow", "First Wt.Date:"))
        self.label_35.setText(_translate("MainWindow", "First Wt.Time:"))
        self.label_36.setText(_translate("MainWindow", "First Wt Ton.:"))
        
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("") 
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Gross"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Tare"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "None"))
        self.label_37.setText(_translate("MainWindow", "Second Wt Ton.:"))
        self.label_38.setText(_translate("MainWindow", "Second Wt. Mode:"))
        self.label_39.setText(_translate("MainWindow", "Second. Wt.Time:"))
        self.label_40.setText(_translate("MainWindow", "Second Wt.Date:"))
        self.label_25.setText(_translate("MainWindow", "Serial. No.:"))
        self.label_26.setText(_translate("MainWindow", "Vehicle No.:"))
        self.label_27.setText(_translate("MainWindow", "Batch Id:"))
        self.label_28.setText(_translate("MainWindow", "Material :"))
        self.label_29.setText(_translate("MainWindow", "Accpted Bags:"))
        self.label_30.setText(_translate("MainWindow", "Contractor Name:"))
        self.label_31.setText(_translate("MainWindow", "Target Location :"))
        self.label_32.setText(_translate("MainWindow", "00001"))
        self.label_41.setText(_translate("MainWindow", "Net.Wt.Ton.:"))
        self.label_42.setText(_translate("MainWindow", "0"))
        self.label_43.setText(_translate("MainWindow", "Site. Sr.No:"))
        self.label_44.setText(_translate("MainWindow", "0000"))
        self.label_45.setText(_translate("MainWindow", "Carried Bags:"))
        self.label_46.setText(_translate("MainWindow", "0"))
        self.pushButton_10.setText(_translate("MainWindow", "Delete"))
        self.label_21.setText(_translate("MainWindow", "Vehicles List"))
        self.pushButton_8.clicked.connect(MainWindow.close)
        
        self.load_data()
        self.list_vehicles()
        #self.lineEdit_3.setText("lineEdit_3")
        #self.lineEdit_4.setText("lineEdit_4")
        #self.lineEdit_12.setText("lineEdit_12")
        self.lineEdit_11.setText("0")
        #self.lineEdit_10.setText("lineEdit_10")
        
        self.lineEdit_9.setText("0")
        #self.lineEdit_8.setText("lineEdit_8")
        #self.lineEdit_7.setText("lineEdit_7")
        
        #self.lineEdit_6.setText("lineEdit_6")
        #self.lineEdit_5.setText("lineEdit_5")
        
        
        self.radioButton_5.clicked.connect(self.serial_no_onlick)
        self.radioButton_3.clicked.connect(self.vehical_onlick)
        self.radioButton_4.clicked.connect(self.batch_onlick)
        self.pushButton_9.clicked.connect(self.list_vehicles)
        self.listWidget.doubleClicked.connect(self.selected_record)
        self.pushButton_7.clicked.connect(self.update_record)
        self.pushButton_10.clicked.connect(self.delete_record)
        self.lineEdit_9.textChanged.connect(self.text_change_first_wt)
        self.lineEdit_11.textChanged.connect(self.text_change_second_wt)
        self.label_24.hide()
    
        self.timer1=QtCore.QTimer()
        self.timer1.setInterval(1000)        
        self.timer1.timeout.connect(self.device_date)
        self.timer1.start(1)
        
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT LOGIN_USER_ID ,LOGIN_USER_ROLE FROM GLOBAL_VAR") 
        for x in results:
            self.login_user_id=str(x[0])
            self.login_user_role=str(x[1])
        connection.close()
        print("self.login_user_role :"+str(self.login_user_role))
    def device_date(self):     
        self.label_20.setText(datetime.datetime.now().strftime("%d %b %Y %H:%M:%S"))
    
    
    def text_change_first_wt(self):
        self.net_wt=0
        if(self.lineEdit_9.text() == "" or self.lineEdit_9.text()=="0" ):
               self.lineEdit_9.setText("0")
        else:
               self.net_wt_calc()
    
    def net_wt_calc(self):
        #print("xxx :"+str(float(self.lineEdit_11.text())))
        if(float(self.lineEdit_11.text()) > 0 ):        
               self.net_wt=int(self.lineEdit_11.text()) - int(self.lineEdit_9.text())
               if(float(self.net_wt) < 0 ):
                       self.net_wt=int(self.net_wt)*(-1)
               self.label_42.setText(str(round(self.net_wt,3)))
               self.net_wt=int(float(self.net_wt/50))
               #self.lineEdit_6.setText(str(self.net_wt))
        
               
               
    def text_change_second_wt(self):
        self.net_wt=0
        if(str(self.lineEdit_11.text()) == "" or str(self.lineEdit_11.text()) == "0"):
               self.lineEdit_11.setText("0")
        else:
               self.net_wt_calc()
            
              
    
    def serial_no_onlick(self):
        self.radioButton_5.setChecked(True) #serial no   
        self.radioButton_4.setChecked(False) # batch 
        self.radioButton_3.setChecked(False) # vehi No 
        
        self.groupBox_6.setEnabled(True) #bat        
        self.groupBox_7.setDisabled(True) #vehical grp        
        self.groupBox_5.setDisabled(True) #ser
    
   
    def vehical_onlick(self):        
        self.radioButton_5.setChecked(False) #serial no   
        self.radioButton_4.setChecked(False) # batch 
        self.radioButton_3.setChecked(True) # vehi No 
        
        self.groupBox_6.setDisabled(True) #bat        
        self.groupBox_7.setDisabled(True) #vehical grp 
        self.groupBox_5.setEnabled(True) #vehi No 
     
    def batch_onlick(self):
        self.radioButton_5.setChecked(False) #serial no   
        self.radioButton_4.setChecked(True) # batch 
        self.radioButton_3.setChecked(False) # vehi No 
        
        self.groupBox_6.setDisabled(True) #bat        
        self.groupBox_7.setEnabled(True) #vehical grp 
        self.groupBox_5.setDisabled(True) #vehi No 
            
  
    
    
    
    
    def load_data(self):
        self.radioButton_5.setChecked(True) #serial no        
        self.radioButton_3.setChecked(False) #vehical no        
        self.radioButton_4.setChecked(False) #batch        
        self.groupBox_6.setEnabled(True) #serial        
        self.groupBox_7.setDisabled(True) #vehical grp        
        self.groupBox_5.setDisabled(True) #batch
        
        
        self.i=0
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT distinct BATCH_ID FROM WEIGHT_MST WHERE BATCH_ID not in ('','None')") 
        for x in results:            
            self.comboBox.addItem("")
            self.comboBox.setItemText(self.i,str(x[0]))
            self.i=self.i+1
        connection.close()
        
        
          
    def list_vehicles(self):        
        self.listWidget.clear()        
        self.listWidget.addItem("==== Weighing List =====")
        connection = sqlite3.connect("fci.db")
        if(self.radioButton_3.isChecked()):  #vehical No            
            if(self.lineEdit_3.text() != ""):
                  self.whr_sql=" and VEHICLE_NO like '%"+str(self.lineEdit_3.text())+"%' order by serial_id desc "
            else:    
                  self.whr_sql=" order by serial_id desc"
            results=connection.execute("SELECT VEHICLE_NO||' - ('||printf(\"%04d\", SERIAL_ID)||')' AS SERIAL_ID FROM WEIGHT_MST WHERE (ifnull(round((julianday(CURRENT_TIMESTAMP) - julianday(FIRST_WT_CRTEATED_ON) )),0) < 365)  "+str(self.whr_sql))
        elif(self.radioButton_4.isChecked()): # batch id
            if(self.comboBox.currentText() != ""):
                  self.whr_sql=" and batch_id = '"+str(self.comboBox.currentText())+"'  order by serial_id desc"
            else:    
                  self.whr_sql=" order by serial_id desc"
            
            #print("PArty :"+str(self.comboBox.currentText()))
            print(" wheresql :"+str(self.whr_sql))      
            results=connection.execute("SELECT VEHICLE_NO||' - ('||printf(\"%04d\", SERIAL_ID)||')' AS SERIAL_ID FROM WEIGHT_MST WHERE (ifnull(round((julianday(CURRENT_TIMESTAMP) - julianday(FIRST_WT_CRTEATED_ON) )),0) < 365) "+str(self.whr_sql))           
        elif(self.radioButton_5.isChecked()):  # Serial No
            if(self.lineEdit_4.text() != ""):
                  self.whr_sql=" and SERIAL_ID like '%"+str(self.lineEdit_4.text())+"%' order by serial_id desc "
            else:    
                  self.whr_sql=" order by serial_id desc"             
            results=connection.execute("SELECT VEHICLE_NO||' - ('||printf(\"%04d\", SERIAL_ID)||')'  AS SERIAL_ID FROM WEIGHT_MST WHERE (ifnull(round((julianday(CURRENT_TIMESTAMP) - julianday(FIRST_WT_CRTEATED_ON) )),0) < 365) "+str(self.whr_sql))
        else:
            results=connection.execute("SELECT VEHICLE_NO||' - ('||printf(\"%04d\", SERIAL_ID)||')'  AS SERIAL_ID FROM WEIGHT_MST WHERE (ifnull(round((julianday(CURRENT_TIMESTAMP) - julianday(FIRST_WT_CRTEATED_ON) )),0) < 365) order by serial_id desc ")
        for x in results:        
               self.listWidget.addItem(str(x[0]))
        connection.close()
    
    
   
    def selected_record(self): 
        self.label_24.hide()
        self.comboBox_2.clear()
        self.comboBox_4.clear()
        self.comboBox_5.clear() 
        self.comboBox_3.clear()
        self.lineEdit_11.setText("0")
        self.lineEdit_9.setText("0")
        self.label_42.setText("0")
        self.i=0
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT distinct BATCH_ID FROM WEIGHT_MST WHERE BATCH_ID not in ('','None')") 
        for x in results:            
            self.comboBox_2.addItem("")
            self.comboBox_2.setItemText(self.i,str(x[0]))
            self.i=self.i+1
        connection.close()
        
        self.i=0
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT M_NAME FROM MATERIAL_TYPES ORDER BY M_NAME DESC ") 
        for x in results:            
            self.comboBox_3.addItem("")
            self.comboBox_3.setItemText(self.i,str(x[0]))            
            self.i=self.i+1
        connection.close()
        
        self.i=0
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT C_NAME FROM CONTRACTOR_MST ORDER BY C_NAME DESC ") 
        for x in results:            
            self.comboBox_4.addItem("")
            self.comboBox_4.setItemText(self.i,str(x[0]))            
            self.i=self.i+1
        connection.close()
        
        
        self.i=0
        connection = sqlite3.connect("fci.db")
        results=connection.execute("SELECT STORAGE_NAME||'-'|| STORAGE_LOCATION  FROM STORAGE_DETAILS ORDER BY STORAGE_NAME  ") 
        for x in results:            
            self.comboBox_5.addItem("")
            self.comboBox_5.setItemText(self.i,str(x[0]))            
            self.i=self.i+1
        connection.close()
        
        
        
        self.list_type=self.listWidget.item(0).text()
        if(self.listWidget.currentItem().text() != self.listWidget.item(0).text()):
            if(self.list_type=="==== Weighing List ====="):
                #print("current test is :"+str(self.listWidget.currentItem().text()))
                self.re_str = str(self.listWidget.currentItem().text())                
                self.serial_id= re.search('\(([^)]+)', self.re_str).group(1)
                print("SErial ID : "+str(int(self.serial_id)))
                connection = sqlite3.connect("fci.db")
                
                
                results=connection.execute("SELECT SERIAL_ID,VEHICLE_NO,MATERIAL_NAME,BATCH_ID,CONTRACTOR_NAME,CURR_TRUCK_CNT,TOTAL_TRUCKS_CNT,ACCPTED_BAGS,TARGET_STORAGE,round(NET_WEIGHT_VAL,2),"+                                           
                                   "FIRST_WEIGHT_MODE,FIRST_WEIGHT_VAL,FIRST_WT_CRTEATED_ON,SECOND_WT_MODE,SECOND_WT_VAL,SECOND_WT_CREATED_ON,IFNULL(MANNUAL_INS_FLG,'')  FROM WEIGHT_MST_FCI_VW where SERIAL_ID = '"+str(int(self.serial_id))+"'")
                for x in results:                    
                    print("ok")
                    self.label_32.setText(str(x[0]).zfill(6))
                    print("role:"+str(self.login_user_role))
                    if(self.login_user_role in ['SUPER_ADMIN','ADMIN','SUPERVISOR']):
                            self.label_25.setText("Serial.No."+str(x[16]))
                    
                    self.lineEdit_5.setText(str(x[1]))
                    self.comboBox_3.setCurrentText(str(x[2]))
                    self.comboBox_2.setCurrentText(str(x[3]))
                    self.comboBox_4.setCurrentText(str(x[4]))
                    self.label_44.setText(str(x[5]))
                    self.label_46.setText(str(x[6]))
                    self.lineEdit_6.setText(str(x[7]))
                    self.comboBox_5.setCurrentText(str(x[8]))
                    #self.label_42.setText(str(x[9]))
                    
                    self.comboBox_6.setCurrentText(str(x[10]))
                    self.lineEdit_9.setText(str(x[11]))
                    self.lineEdit_7.setText(str(x[12])[0:10])
                    self.lineEdit_8.setText(str(x[12])[11:16])
                    
                    self.comboBox_7.setCurrentText(str(x[13]))
                    self.lineEdit_11.setText(str(x[14]))
                    self.lineEdit_10.setText(str(x[15])[0:10])
                    self.lineEdit_12.setText(str(x[15])[11:16])
                    self.net_wt_calc()
                    
               
            else:             
                print("Invalid !!")
                
    def update_record(self):
            self.label_24.show()            
            #print("UPDATE WEIGHT_MST SET VEHICLE_NO="+str(self.lineEdit_5.text())+",PARTY_NAME="+str(self.lineEdit_7.text())+",FPRM_NO="+str(self.lineEdit_9.text())+",REMARK="+str(self.lineEdit_10.text())+",FIRST_WEIGHT_MODE="+self.comboBox_2.currentText()+",FIRST_WEIGHT_VAL="+str(self.lineEdit_14.text())+",SECOND_WT_MODE="+self.comboBox_3.currentText()+",SECOND_WT_VAL="+str(self.lineEdit_17.text())+"    WHERE SERIAL_ID='"+str(int(self.label_25.text()))+"'")       
            connection = sqlite3.connect("fci.db")          
            with connection:        
                         cursor = connection.cursor()                    
                         cursor.execute("UPDATE WEIGHT_MST SET MATERIAL_NAME='"+self.comboBox_3.currentText()+"',BATCH_ID='"+self.comboBox_2.currentText()+"',CONTRACTOR_NAME='"+self.comboBox_4.currentText()+"',CURR_TRUCK_CNT='"+self.label_44.text()+"',TOTAL_TRUCKS_CNT='"+self.label_46.text()+"',ACCPTED_BAGS='"+self.lineEdit_6.text()+"',TARGET_STORAGE='"+self.comboBox_5.currentText()+"',NET_WEIGHT_VAL='"+self.label_42.text()+"',VEHICLE_NO='"+str(self.lineEdit_5.text())+"',FIRST_WEIGHT_MODE='"+self.comboBox_6.currentText()
                                        +"',FIRST_WEIGHT_VAL='"+str(self.lineEdit_9.text())+"',SECOND_WT_MODE='"+self.comboBox_7.currentText()+"',SECOND_WT_VAL='"
                                        +str(self.lineEdit_11.text())+"' ,UPDATED_BY='"+str(self.login_user_id)+"', UPDATED_ON=current_timestamp ,EDITED_FLG='Yes' WHERE SERIAL_ID='"
                                        +str(int(self.label_32.text()))+"'") 
            connection.commit();
            connection.close()
            print("Record updated"+str(int(self.label_32.text())))
            self.label_24.setText("Saved Successfully.")
            self.log_audit("Update/Delete Weighing","Updated Slip No :" +str(self.label_32.text()))
            
  
    
    def delete_record(self):
           close = QMessageBox()
           close.setText("This would remove important data from system.Are You Sure Want to Delete ? ")
           close.setStandardButtons(QMessageBox.Yes | QMessageBox.Cancel)
           close = close.exec()
           if close == QMessageBox.Yes:                
                   self.label_24.show()
                   connection = sqlite3.connect("fci.db")          
                   with connection:        
                                 cursor = connection.cursor()                    
                                 cursor.execute("DELETE FROM  WEIGHT_MST WHERE SERIAL_ID='"+str(int(self.label_32.text()))+"'") 
                   connection.commit();
                   connection.close()
                   self.list_vehicles()
                   self.label_24.setText("Deleted  Successfully.")
                   self.log_audit("Update/Delete Weighing","Deleted Slip No :" +str(self.label_32.text()))
           else:
                  self.label_24.setText("Cancled Delete")
           
        
    def log_audit(self,event_name,desc_str):        
        connection = sqlite3.connect("fci.db")
        with connection:        
            cursor = connection.cursor()       
            cursor.execute("INSERT INTO AUDIT_MST(AUDIT_TYPE,MESSAGE) VALUES(?,?)",(event_name,desc_str))
            cursor.execute("UPDATE AUDIT_MST SET USER_ID = (SELECT LOGIN_USER_ID FROM GLOBAL_VAR) WHERE USER_ID IS NULL")
            
        connection.commit();
        connection.close()   

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = fci_25_Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
