CREATE TABLE `issue_mst` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ISSUE_ID` varchar(45) DEFAULT NULL,
  `ORDER_ID` varchar(145) DEFAULT NULL,
  `ISSUE_DATE` datetime DEFAULT NULL,
  `EXPIRY_DATE` datetime DEFAULT NULL,
  `RO_TYPE` varchar(145) DEFAULT NULL,
  `ORDER_TYPE` varchar(45) DEFAULT NULL,
  `CONTRACTOR_NAME` varchar(145) DEFAULT NULL,
  `TOTAL_BAGS_DEMAND` varchar(45) DEFAULT NULL,
  `TOTAL_NET_WT_DEMAND` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_ON` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_ON` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `DEVICE_ID` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ;
