
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import serial,time
from PyQt5.QtCore import QDate
import datetime
import sys
import os
'''
print("started !!!")
connection = sqlite3.connect("tyr.db")        
with connection:        
                cursor = connection.cursor()                
                cursor.execute("update TEST_MST set COMMENTS='ok' WHERE TEST_ID IN (SELECT EMAIL_TEST_ID FROM GLOBAL_VAR)")                 
connection.commit()
connection.close()
print("Completed !!!")
'''
print("started !!!")
TEST_ID=1039  #Max current test id
GRAPH_ID=1047  # MAx current graph id 
connection = sqlite3.connect("tyr.db")        
with connection:
            cursor = connection.cursor()
            for k in range(1000):
                INST_TEST_MST = "INSERT INTO TEST_MST (TEST_ID,TEST_TYPE,SPECIMEN_NAME,JOB_NAME,BATCH_ID,MOTOR_SPEED,MOTOR_REV_SPEED,GUAGE_LENGTH,PARTY_NAME,STATUS,GRAPH_SCAL_Y_LOAD,GRAPH_SCAL_Y_LOAD_N,GRAPH_SCAL_Y_LOAD_LB,GRAPH_SCAL_X_LENGTH,GRAPH_SCAL_X_LENGTH_CM,GRAPH_SCAL_X_LENGTH_INCH,TESTED_BY,TEST_METHOD,LAST_UNIT_LOAD,LAST_UNIT_DISP) select '"+str(TEST_ID)+"',TEST_TYPE,SPECIMEN_NAME,JOB_NAME,BATCH_ID,MOTOR_SPEED,MOTOR_REV_SPEED,GUAGE_LENGTH,PARTY_NAME,STATUS,GRAPH_SCAL_Y_LOAD,GRAPH_SCAL_Y_LOAD_N,GRAPH_SCAL_Y_LOAD_LB,GRAPH_SCAL_X_LENGTH,GRAPH_SCAL_X_LENGTH_CM,GRAPH_SCAL_X_LENGTH_INCH,TESTED_BY,TEST_METHOD,LAST_UNIT_LOAD,LAST_UNIT_DISP  from TEST_MST WHERE TEST_ID=1"
                INST_CYCLES_MST="INSERT INTO CYCLES_MST (TEST_ID,CYCLE_NUM,GRAPH_ID,SHAPE,THINCKNESS, WIDTH,CS_AREA,PEAK_LOAD_KG,PEAK_LOAD_N,E_AT_PEAK_LOAD_MM,PRC_E_AT_BREAK,BREAK_LOAD_KG,PEAK_LOAD_KG,PEAK_LOAD_N,E_AT_PEAK_LOAD_MM,PRC_E_AT_PEAK,BREAK_LOAD_KG,E_AT_BREAK_MM,PRC_E_AT_BREAK,SET_LOW,DIAMETER,INNER_DIAMETER,OUTER_DIAMETER,TENSILE_STRENGTH,GUAGE100,LOAD100_GUAGE,MODULUS_100,GUAGE200,LOAD200_GUAGE,MODULUS_200,GUAGE300,LOAD300_GUAGE,MODULUS_300,STG_TENSILE_STRENGTH_KG_CM,STG_TENSILE_STRENGTH_LB_INCH,STG_TENSILE_STRENGTH_N_MM,STG_TENSILE_STRENGTH_MPA) select '"+str(TEST_ID)+"',CYCLE_NUM,'"+str(GRAPH_ID)+"',SHAPE,THINCKNESS, WIDTH,CS_AREA,PEAK_LOAD_KG,PEAK_LOAD_N,E_AT_PEAK_LOAD_MM,PRC_E_AT_BREAK,BREAK_LOAD_KG,PEAK_LOAD_KG,PEAK_LOAD_N,E_AT_PEAK_LOAD_MM,PRC_E_AT_PEAK,BREAK_LOAD_KG,E_AT_BREAK_MM,PRC_E_AT_BREAK,SET_LOW,DIAMETER,INNER_DIAMETER,OUTER_DIAMETER,TENSILE_STRENGTH,GUAGE100,LOAD100_GUAGE,MODULUS_100,GUAGE200,LOAD200_GUAGE,MODULUS_200,GUAGE300,LOAD300_GUAGE,MODULUS_300,STG_TENSILE_STRENGTH_KG_CM,STG_TENSILE_STRENGTH_LB_INCH,STG_TENSILE_STRENGTH_N_MM,STG_TENSILE_STRENGTH_MPA  from CYCLES_MST WHERE TEST_ID=1"
                INST_GRAPH_MST="INSERT INTO GRAPH_MST (GRAPH_ID,X_NUM,X_NUM_CM,X_NUM_INCH,Y_NUM,Y_NUM_KN,Y_NUM_LB,Y_NUM_LB,Y_NUM_MPA) select '"+str(GRAPH_ID)+"',X_NUM,X_NUM_CM,X_NUM_INCH,Y_NUM,Y_NUM_KN,Y_NUM_LB,Y_NUM_LB,Y_NUM_MPA from GRAPH_MST WHERE GRAPH_ID=1"
                cursor.execute(str(INST_TEST_MST))
                cursor.execute(str(INST_CYCLES_MST))
                cursor.execute(str(INST_GRAPH_MST))
                print("TEST_ID ===>"+str(TEST_ID))
                print("GRAPH_ID ===>"+str(GRAPH_ID))
                TEST_ID=TEST_ID+1
                GRAPH_ID=GRAPH_ID+1                
connection.commit()
connection.close()
print("Completed !!!")