import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.Qt import QTableWidgetItem
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

class TY_05_SPEC_8_Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 768)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 1321, 711))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(255, 237, 250);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 85, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(1090, 30, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(170, 85, 127);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 650, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-style:outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(226, 239, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 650, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-style:outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(226, 239, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 100, 641, 531))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(226, 255, 225);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(3)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(18)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(14, item)
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(15, item)
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(16, item)
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(17, item)
        
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setItem(0, 17, item)
        
        
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(390, 30, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(1000, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(680, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(680, 450, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit)
        self.lineEdit.setValidator(input_validator)
        self.lineEdit.setGeometry(QtCore.QRect(1110, 400, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_3)
        self.lineEdit_3.setValidator(input_validator)
        self.lineEdit_3.setGeometry(QtCore.QRect(810, 450, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 650, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-style:outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(226, 239, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 650, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border-style:outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(226, 239, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(1130, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(1020, 400, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(1000, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_4)
        self.lineEdit_4.setValidator(input_validator)
        self.lineEdit_4.setGeometry(QtCore.QRect(810, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(690, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_10)
        self.lineEdit_10.setValidator(input_validator)
        self.lineEdit_10.setGeometry(QtCore.QRect(810, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(490, 650, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("border-style:outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(226, 239, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_12.setGeometry(QtCore.QRect(1130, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(810, 400, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(1030, 450, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_6)
        self.lineEdit_6.setValidator(input_validator)
        self.lineEdit_6.setGeometry(QtCore.QRect(1110, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(1000, 230, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(690, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(680, 90, 621, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(690, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(810, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 85, 127);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(900, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(690, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_5)
        self.lineEdit_5.setValidator(input_validator)
        self.lineEdit_5.setGeometry(QtCore.QRect(810, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(900, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(self.frame)
        self.label_39.setGeometry(QtCore.QRect(900, 290, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame)
        self.label_40.setGeometry(QtCore.QRect(880, 450, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame)
        self.label_41.setGeometry(QtCore.QRect(1210, 400, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame)
        self.label_42.setGeometry(QtCore.QRect(1210, 450, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(1130, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(690, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border-style:outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(226, 239, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(820, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("border-style:outset;\n"
"border-color: rgb(0, 0, 0);\n"
"border-width:4px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius:20px;\n"
"background-color: rgb(226, 239, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(680, 360, 621, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line_3.setFont(font)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.label_47 = QtWidgets.QLabel(self.frame)
        self.label_47.setGeometry(QtCore.QRect(1000, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(1130, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(680, 500, 621, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line_4.setFont(font)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.label_49 = QtWidgets.QLabel(self.frame)
        self.label_49.setGeometry(QtCore.QRect(690, 530, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(810, 530, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_50 = QtWidgets.QLabel(self.frame)
        self.label_50.setGeometry(QtCore.QRect(900, 530, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: rgb(0, 0, 255);\n"
"color: rgb(0, 85, 0);")
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_8)
        self.lineEdit_8.setValidator(input_validator)
        self.lineEdit_8.setGeometry(QtCore.QRect(990, 530, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_11)
        self.lineEdit_11.setValidator(input_validator)
        self.lineEdit_11.setGeometry(QtCore.QRect(1160, 530, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_51 = QtWidgets.QLabel(self.frame)
        self.label_51.setGeometry(QtCore.QRect(900, 590, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(0, 0, 255);\n"
"color: rgb(0, 85, 0);")
        self.label_51.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.label_43 = QtWidgets.QLabel(self.frame)
        self.label_43.setGeometry(QtCore.QRect(1050, 530, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame)
        self.label_44.setGeometry(QtCore.QRect(1220, 530, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_13)
        self.lineEdit_13.setValidator(input_validator)
        self.lineEdit_13.setGeometry(QtCore.QRect(990, 590, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_14)
        self.lineEdit_14.setValidator(input_validator)
        self.lineEdit_14.setGeometry(QtCore.QRect(990, 660, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_15)
        self.lineEdit_15.setValidator(input_validator)
        self.lineEdit_15.setGeometry(QtCore.QRect(1160, 590, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame)
        reg_ex = QRegExp("\\d+\\.\\d+")
        input_validator = QRegExpValidator(reg_ex, self.lineEdit_16)
        self.lineEdit_16.setValidator(input_validator)
        self.lineEdit_16.setGeometry(QtCore.QRect(1160, 660, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_52 = QtWidgets.QLabel(self.frame)
        self.label_52.setGeometry(QtCore.QRect(900, 660, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(0, 0, 255);\n"
"color: rgb(0, 85, 0);")
        self.label_52.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.label_45 = QtWidgets.QLabel(self.frame)
        self.label_45.setGeometry(QtCore.QRect(1050, 590, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame)
        self.label_46.setGeometry(QtCore.QRect(1220, 590, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.label_48 = QtWidgets.QLabel(self.frame)
        self.label_48.setGeometry(QtCore.QRect(1050, 660, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.label_53 = QtWidgets.QLabel(self.frame)
        self.label_53.setGeometry(QtCore.QRect(1220, 660, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_53.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Specimen Information(8)"))
        self.label_20.setText(_translate("MainWindow", "05 Aug 2020 12:45:00"))
        self.pushButton_2.setText(_translate("MainWindow", "Add"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Spec.ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Test Mode"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Load Cell"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Specimen"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Party"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Guage Length \\n (mm)"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Others"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Test.Speed \\n (mm/min)"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Rev.Speed \\n (mm/min)"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Thickness"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Width"))
        item = self.tableWidget.horizontalHeaderItem(12)
        
        item.setText(_translate("MainWindow", "Range_1_From"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Range_1_To"))
        
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Range_2_From"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Range_2_To"))
        
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Range_3_From"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Range_3_To"))
        
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "w"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Rectangle"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "ee"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "e"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "222ewe"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("MainWindow", "23"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_21.setText(_translate("MainWindow", "Please select the record to Edit."))
        self.label_22.setText(_translate("MainWindow", "Product.Name :"))
        self.label_24.setText(_translate("MainWindow", "Specimen:"))
        self.label_25.setText(_translate("MainWindow", "Thickness:"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.lineEdit_3.setText(_translate("MainWindow", "1"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete"))
        self.pushButton_5.setText(_translate("MainWindow", "Reset"))
        self.lineEdit_7.setText(_translate("MainWindow", "party"))
        self.label_31.setText(_translate("MainWindow", "Pre. Load:"))
        self.label_33.setText(_translate("MainWindow", "Party:"))
        self.lineEdit_4.setText(_translate("MainWindow", "200"))
        self.label_34.setText(_translate("MainWindow", "Guage Length:"))
        self.lineEdit_10.setText(_translate("MainWindow", "0.1"))
        self.pushButton_9.setText(_translate("MainWindow", "Return"))
        self.lineEdit_12.setText(_translate("MainWindow", "sec name"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Rectrangle"))
        self.label_27.setText(_translate("MainWindow", "Width:"))
        self.lineEdit_6.setText(_translate("MainWindow", "2"))
        self.label_26.setText(_translate("MainWindow", "Others:"))
        self.label_35.setText(_translate("MainWindow", "Test Speed:"))
        self.label_23.setText(_translate("MainWindow", "Spect.ID:"))
        self.label_2.setText(_translate("MainWindow", "0001"))
        self.label_28.setText(_translate("MainWindow", "(mm/min)"))
        self.label_36.setText(_translate("MainWindow", "Rev. Speed:"))
        self.lineEdit_5.setText(_translate("MainWindow", "200"))
        self.label_37.setText(_translate("MainWindow", "(mm/min)"))
        self.label_39.setText(_translate("MainWindow", "(mm)"))
        self.label_40.setText(_translate("MainWindow", "(mm)"))
        self.label_41.setText(_translate("MainWindow", "Kg"))
        self.label_42.setText(_translate("MainWindow", "(mm)"))
        '''
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TM -00JT002</p></body></html>"))
        '''
        self.pushButton_6.setText(_translate("MainWindow", "Export"))
        self.pushButton_7.setText(_translate("MainWindow", "Import"))
        self.label_47.setText(_translate("MainWindow", "Test Mode:"))
        self.radioButton_2.setText(_translate("MainWindow", "Compression"))
        self.label_49.setText(_translate("MainWindow", "Load Cell:"))
        self.lineEdit_9.setText(_translate("MainWindow", "5KN"))
        self.label_50.setText(_translate("MainWindow", "Range-1:"))
        self.lineEdit_8.setText(_translate("MainWindow", "2.5"))
        self.lineEdit_11.setText(_translate("MainWindow", "5.7"))
        self.label_51.setText(_translate("MainWindow", "Range-2:"))
        self.label_43.setText(_translate("MainWindow", "(mm)"))
        self.label_44.setText(_translate("MainWindow", "(mm)"))
        self.lineEdit_13.setText(_translate("MainWindow", "3.6"))
        self.lineEdit_14.setText(_translate("MainWindow", "8.6"))
        self.lineEdit_15.setText(_translate("MainWindow", "6.6"))
        self.lineEdit_16.setText(_translate("MainWindow", "16"))
        self.label_52.setText(_translate("MainWindow", "Range-3:"))
        self.label_45.setText(_translate("MainWindow", "(mm)"))
        self.label_46.setText(_translate("MainWindow", "(mm)"))
        self.label_48.setText(_translate("MainWindow", "(mm)"))
        self.label_53.setText(_translate("MainWindow", "(mm)"))
        self.timer1=QtCore.QTimer()
        self.timer1.start(1)
        self.timer1.setInterval(1000)        
        self.timer1.timeout.connect(self.setDateAndTime)
        self.pushButton_9.clicked.connect(MainWindow.close)
        self.pushButton_5.clicked.connect(self.resetFields)
        self.pushButton_2.clicked.connect(self.addSpecimen)
        self.pushButton_3.clicked.connect(self.saveSpecimen)
        self.pushButton_4.clicked.connect(self.deleteSpecimen)
        self.tableWidget.doubleClicked.connect(self.fetchSpecimenData)

        self.pushButton_2.setDisabled(True)
        self.pushButton_3.setDisabled(True)
        self.pushButton_4.setDisabled(True)
        self.label_21.hide()
        self.loadData()
        self.lineEdit_12.setReadOnly(True)

    
    def loadData(self):
        self.delete_all_records()
        connection = sqlite3.connect("tyr.db")
        results = connection.execute("SELECT SPECIMEN_ID, SPECIMEN_NAME, LOAD_CELL, SHAPE, PARTY_NAME, GUAGE_LENGTH_MM, SPECIMEN_SPECS, MOTOR_SPEED, REV_MOTOR_SPEED, PRE_LOAD, THICKNESS,WIDTH,ifnull(RANGE_1_FROM,0),ifnull(RANGE_1_TO,0),ifnull(RANGE_2_FROM,0),ifnull(RANGE_2_TO,0),ifnull(RANGE_3_FROM,0),ifnull(RANGE_3_TO,0) FROM SPECIMEN_MST")
        for row_number, row_data in enumerate(results):            
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data): 
                self.tableWidget.setItem(row_number,column_number,QTableWidgetItem(str (data))) 
        connection.commit()
        connection.close()
        if(self.tableWidget.rowCount() > 0):
                self.label_2.setText(str(self.tableWidget.item(0, 0).text().zfill(3)))   #Spect.ID:
                self.lineEdit_12.setText(str(self.tableWidget.item(0, 1).text()))  #Product.Name : SPECIMEN_NAME
                self.lineEdit_9.setText(str(self.tableWidget.item(0, 2).text()))  #Load Cell:
                
                self.lineEdit_7.setText(str(self.tableWidget.item(0, 4).text()))   #Party:
                self.lineEdit_10.setText(str(self.tableWidget.item(0, 5).text())) #Guage Length:
                
                self.textEdit.setText(str(self.tableWidget.item(0, 6).text()))  #Others:  SPECIMEN_SPECS
                self.lineEdit_4.setText(str(self.tableWidget.item(0, 7).text()))  #Test Speed:
                self.lineEdit_5.setText(str(self.tableWidget.item(0, 8).text()))  #Rev. Speed:
                
                self.lineEdit.setText(str(self.tableWidget.item(0, 9).text()))    #Pre. Load:  
                self.lineEdit_3.setText(str(self.tableWidget.item(0, 10).text()))  #Thickness:               
                self.lineEdit_6.setText(str(self.tableWidget.item(0, 11).text()))  #Width:
                
                self.comboBox_2.setCurrentIndex(0)  #Shape:
                
                self.lineEdit_8.setText(str(self.tableWidget.item(0, 12).text()))  
                self.lineEdit_11.setText(str(self.tableWidget.item(0, 13).text()))  
                self.lineEdit_13.setText(str(self.tableWidget.item(0, 14).text()))  
                self.lineEdit_15.setText(str(self.tableWidget.item(0, 15).text()))  
                self.lineEdit_14.setText(str(self.tableWidget.item(0, 16).text()))  
                self.lineEdit_16.setText(str(self.tableWidget.item(0, 17).text()))
                
                
    def fetchSpecimenData(self):
        self.lineEdit_12.setReadOnly(True)
        self.pushButton_2.setDisabled(True)
        self.pushButton_3.setDisabled(False)
        self.pushButton_4.setDisabled(False)  
        row = self.tableWidget.currentRow() 
        if (row != -1):
                '''
                self.label_2.setText(str(self.tableWidget.item(row, 0).text().zfill(3)))   #Spect.ID:
                self.lineEdit_4.setText(str(self.tableWidget.item(row, 8).text()))  #Test Speed:
                self.lineEdit_5.setText(str(self.tableWidget.item(row, 9).text()))  #Rev. Speed:
                self.lineEdit_10.setText(str(self.tableWidget.item(row, 6).text())) #Guage Length:
                self.lineEdit_12.setText(str(self.tableWidget.item(row, 1).text()))  #Product.Name : SPECIMEN_NAME
                self.lineEdit_7.setText(str(self.tableWidget.item(row, 5).text()))   #Party:
                self.textEdit.setText(str(self.tableWidget.item(row, 7).text()))  #Others:  SPECIMEN_SPECS
                self.lineEdit_3.setText(str(self.tableWidget.item(row, 11).text()))  #Thickness:
                self.lineEdit.setText(str(self.tableWidget.item(row, 10).text()))    #Pre. Load:
                #self.lineEdit_6.setText(str(self.tableWidget.item(row, 12).text()))  #Width:
                self.lineEdit_9.setText(str(self.tableWidget.item(row, 3).text()))  #Load Cell:
                '''
                self.label_2.setText(str(self.tableWidget.item(row, 0).text().zfill(3)))   #Spect.ID:
                self.lineEdit_12.setText(str(self.tableWidget.item(row, 1).text()))  #Product.Name : SPECIMEN_NAME
                self.lineEdit_9.setText(str(self.tableWidget.item(row, 2).text()))  #Load Cell:
                
                self.lineEdit_7.setText(str(self.tableWidget.item(row, 4).text()))   #Party:
                self.lineEdit_10.setText(str(self.tableWidget.item(row, 5).text())) #Guage Length:
                
                self.textEdit.setText(str(self.tableWidget.item(row, 6).text()))  #Others:  SPECIMEN_SPECS
                self.lineEdit_4.setText(str(self.tableWidget.item(row, 7).text()))  #Test Speed:
                self.lineEdit_5.setText(str(self.tableWidget.item(row, 8).text()))  #Rev. Speed:
                
                self.lineEdit.setText(str(self.tableWidget.item(row, 9).text()))    #Pre. Load:  
                self.lineEdit_3.setText(str(self.tableWidget.item(row, 10).text()))  #Thickness:               
                self.lineEdit_6.setText(str(self.tableWidget.item(row, 11).text()))  #Width:
                
                self.lineEdit_8.setText(str(self.tableWidget.item(row, 12).text()))  
                self.lineEdit_11.setText(str(self.tableWidget.item(row, 13).text()))  
                self.lineEdit_13.setText(str(self.tableWidget.item(row, 14).text()))  
                self.lineEdit_15.setText(str(self.tableWidget.item(row, 15).text()))  
                self.lineEdit_14.setText(str(self.tableWidget.item(row, 16).text()))  
                self.lineEdit_16.setText(str(self.tableWidget.item(row, 17).text()))  
                
                self.comboBox_2.setCurrentIndex(0)  #Shape:
                   
    def delete_all_records(self):
        i = self.tableWidget.rowCount()       
        while (i>0):      
            i=i-1
            self.tableWidget.removeRow(i)
    def resetFields(self):
        self.lineEdit_12.setReadOnly(False)
        self.label_21.hide()
        
        self.pushButton_2.setDisabled(False)
        self.pushButton_3.setDisabled(True)
        self.pushButton_4.setDisabled(True)
        self.label_2.setText("")   #Spect.ID:
        self.lineEdit_4.setText("")  #Test Speed:
        self.lineEdit_5.setText("")  #Rev. Speed:
        self.lineEdit_10.setText("") #Guage Length:
        self.lineEdit_12.setText("")  #Product.Name : SPECIMEN_NAME
        self.lineEdit_7.setText("")   #Party:
        self.textEdit.setText("")  #Others:  SPECIMEN_SPECS
        self.lineEdit_3.setText("")  #Thickness:
        self.lineEdit.setText("")    #Pre. Load:
        self.lineEdit_6.setText("")  #Width:
        self.lineEdit_9.setText("")  #Load Cell:
        self.comboBox_2.setCurrentIndex(0)  #Shape:
        connection = sqlite3.connect("tyr.db")
        results=connection.execute("select seq + 1 from sqlite_sequence WHERE name = 'SPECIMEN_MST'")       
        for x in results:      
                self.label_2.setText(str(x[0]).zfill(3))   
        connection.close()

    def deleteSpecimen(self):
        if(self.label_2.text() != ""):
            close = QMessageBox()
            close.setText("Confirm Deleteing SpecimenID : "+str(self.label_2.text()))
            close.setStandardButtons(QMessageBox.Yes | QMessageBox.Cancel)
            close = close.exec()
            if close == QMessageBox.Yes:
                    connection = sqlite3.connect("tyr.db")
                    with connection:        
                            cursor = connection.cursor()
                            cursor.execute("DELETE FROM SPECIMEN_MST WHERE SPECIMEN_ID ='"+str(self.label_2.text()+"'") )                   
                    connection.commit()                    
                    connection.close()
                    
                    self.label_21.setText("Record Deleted Successfully.")                   
                    self.label_21.show()                    
                    self.loadData()
            else:
                    self.label_21.setText("Canceled Delete..")                   
                    self.label_21.show()
 
         
    def validation(self):
        self.go_ahead="No"
        self.msg=""     
        if not self.msg:
                if (self.lineEdit_4.text() == ""):
                        self.msg = "Test Speed: Should Not Be Empty..."             
                      
                elif (self.lineEdit_5.text() == ""):
                        self.msg="Rev. Speed: Should Not Be Empty..."                
                        
                elif (self.lineEdit_10.text() == ""):
                        self.msg="Guage Length: Should Not Be Empty..."                   
                
                elif (self.lineEdit_12.text() == ""):
                        self.msg="Product Name: Should Not Be Empty..."                   
                
                elif (self.lineEdit_7.text() == ""):
                        self.msg="Party: Should Not Be Empty..."                   
               
                elif (self.textEdit.toPlainText() == ""):
                        self.msg="others: Should Not Be Empty..."                   
                
                elif (self.lineEdit_3.text() == ""):
                        self.msg.setText("Thickness: Should Not Be Empty...")                   
               
                elif (self.lineEdit.text() == ""):
                        self.msg="Pre. Load: Should Not Be Empty..."                   
               
                elif (self.lineEdit_6.text() == ""):
                        self.msg="Width: Should Not Be Empty..."                   
              
                elif (self.lineEdit_9.text() == ""):
                        self.msg="Load Cell: Should Not Be Empty..."
                
                elif (self.lineEdit_8.text() == ""):
                        self.msg="Range: Should Not Be Empty..."
                elif (self.lineEdit_11.text() == ""):
                        self.msg="Range: Should Not Be Empty..."
                elif (self.lineEdit_13.text() == ""):
                        self.msg="Range: Should Not Be Empty..."
                elif (self.lineEdit_14.text() == ""):
                        self.msg="Range: Should Not Be Empty..."
                elif (self.lineEdit_15.text() == ""):
                        self.msg="Range: Should Not Be Empty..."
                elif (self.lineEdit_16.text() == ""):
                        self.msg="Range: Should Not Be Empty..."
                        
                else:
                        self.go_ahead = "Yes"


    def saveSpecimen(self):
        self.validation()        
        close = QMessageBox()
        close.setText("Message:  Click Ok to Update....")
        close.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        close = close.exec()
        if close == QMessageBox.Ok:
                if(self.go_ahead=="Yes"): 
                        try:
                            connection = sqlite3.connect("tyr.db")
                            with connection:
                                    cursor = connection.cursor()
                                    
                                    #print("UPDATE SPECIMEN_MST SET MOTOR_SPEED = ?, REV_MOTOR_SPEED = ?, GUAGE_LENGTH_MM = ?, SPECIMEN_NAME = ?, PARTY_NAME = ?, SPECIMEN_SPECS = ?, THICKNESS = ?, PRE_LOAD = ?, WIDTH = ?, LOAD_CELL = ?, SHAPE = ?, TEST_MODE = ?, RANGE_1_FROM = ?, RANGE_1_TO=?, RANGE_2_FROM = ?, RANGE_2_TO=?, RANGE_3_FROM = ?, RANGE_3_TO=? WHERE SPECIMEN_ID = ?" , (str(self.lineEdit_4.text()), str(self.lineEdit_5.text()), str(self.lineEdit_10.text()), str(self.lineEdit_12.text()), str(self.lineEdit_7.text()), str(self.textEdit.toPlainText()), str(self.lineEdit_3.text()), str(self.lineEdit.text()), str(self.lineEdit_6.text()), str(self.lineEdit_9.text()), 'Rectrangle', 'Compression', str(self.label_2.text()), str(self.lineEdit_8.text()), str(self.lineEdit_11.text()), str(self.lineEdit_13.text()), str(self.lineEdit_15.text()), str(self.lineEdit_14.text()), str(self.lineEdit_16.text())) )
                            
                                    #cursor.execute("UPDATE SPECIMEN_MST SET MOTOR_SPEED = ?, REV_MOTOR_SPEED = ?, GUAGE_LENGTH_MM = ?, SPECIMEN_NAME = ?, PARTY_NAME = ?, SPECIMEN_SPECS = ?, THICKNESS = ?, PRE_LOAD = ?, WIDTH = ?, LOAD_CELL = ?, SHAPE = ?, TEST_MODE = ?, RANGE_1_FROM = ?, RANGE_1_TO= ?, RANGE_2_FROM = ?, RANGE_2_TO=?, RANGE_3_FROM = ?, RANGE_3_TO= ? WHERE SPECIMEN_ID = ?", (str(self.lineEdit_4.text()), str(self.lineEdit_5.text()), str(self.lineEdit_10.text()), str(self.lineEdit_12.text()), str(self.lineEdit_7.text()), str(self.textEdit.toPlainText()), str(self.lineEdit_3.text()), str(self.lineEdit.text()), str(self.lineEdit_6.text()), str(self.lineEdit_9.text()), 'Rectangle', 'Compression', str(self.label_2.text()), str(self.lineEdit_8.text()), str(self.lineEdit_11.text()), str(self.lineEdit_13.text()), str(self.lineEdit_15.text()), str(self.lineEdit_14.text()), str(self.lineEdit_16.text()) ))
                                    cursor.execute("UPDATE SPECIMEN_MST SET MOTOR_SPEED = '"+str(self.lineEdit_4.text())+"', REV_MOTOR_SPEED = '"+str(self.lineEdit_5.text())+"', GUAGE_LENGTH_MM = '"+str(self.lineEdit_10.text())+"', SPECIMEN_NAME = '"+str(self.lineEdit_12.text())+"', PARTY_NAME = '"+str(self.lineEdit_7.text())+"', SPECIMEN_SPECS = '"+str(self.textEdit.toPlainText())+"', THICKNESS = '"+str(self.lineEdit_3.text())+"', PRE_LOAD = '"+str(self.lineEdit.text())+"', WIDTH = '"+str(self.lineEdit_6.text())+"', LOAD_CELL = '"+str(self.lineEdit_9.text())+"', SHAPE = 'Rectangle', TEST_MODE = 'Compression', RANGE_1_FROM = '"+str(self.lineEdit_8.text())+"', RANGE_1_TO= '"+str(self.lineEdit_11.text())+"', RANGE_2_FROM = '"+str(self.lineEdit_13.text())+"', RANGE_2_TO='"+str(self.lineEdit_15.text())+"', RANGE_3_FROM = '"+str(self.lineEdit_14.text())+"', RANGE_3_TO= '"+str(self.lineEdit_16.text())+"' WHERE SPECIMEN_ID = '"+str(self.label_2.text())+"'")
                                                   
                                                   #, (, str(self.lineEdit_5.text()), str(self.lineEdit_10.text()), str(self.lineEdit_12.text()), str(self.lineEdit_7.text()), str(self.textEdit.toPlainText()), str(self.lineEdit_3.text()), str(self.lineEdit.text()), str(self.lineEdit_6.text()), str(self.lineEdit_9.text()), 'Rectangle', 'Compression', str(self.label_2.text()), str(self.lineEdit_8.text()), str(self.lineEdit_11.text()), str(self.lineEdit_13.text()), str(self.lineEdit_15.text()), str(self.lineEdit_14.text()), str(self.lineEdit_16.text()) ))
                            
                                    print("ok ...saved")
                            connection.commit()
                            connection.close()
                        except IOError as e:
                            print("Error... : "+str(e))
                        self.label_21.setText("Specimen Saved.")
                        self.label_21.show()
                        self.loadData()
            
    def addSpecimen(self):
        self.validation()        
        close = QMessageBox()
        close.setText("Message: Confirm to add specimen..")
        close.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        close = close.exec()
        if close == QMessageBox.Ok:
                if(self.go_ahead=="Yes"): 
                        connection = sqlite3.connect("tyr.db")
                        with connection:
                                cursor = connection.cursor()
                                cursor.execute("INSERT INTO SPECIMEN_MST (MOTOR_SPEED, REV_MOTOR_SPEED, GUAGE_LENGTH_MM, SPECIMEN_NAME, PARTY_NAME, SPECIMEN_SPECS, THICKNESS, PRE_LOAD, WIDTH, LOAD_CELL, SHAPE, TEST_MODE,RANGE_1_FROM,RANGE_1_TO,RANGE_2_FROM,RANGE_2_TO,RANGE_3_FROM,RANGE_3_TO) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", (str(self.lineEdit_4.text()), str(self.lineEdit_5.text()), str(self.lineEdit_10.text()), str(self.lineEdit_12.text()), str(self.lineEdit_7.text()), str(self.textEdit.toPlainText()), str(self.lineEdit_3.text()), str(self.lineEdit.text()), str(self.lineEdit_6.text()), str(self.lineEdit_9.text()), 'Rectrangle', 'Compression', str(self.lineEdit_8.text()), str(self.lineEdit_11.text()), str(self.lineEdit_13.text()), str(self.lineEdit_15.text()), str(self.lineEdit_14.text()), str(self.lineEdit_16.text())))
                        connection.commit()
                        connection.close()
                        self.label_21.setText("Specimen Added.....")
                        self.label_21.show()
                        self.loadData()
    def setDateAndTime(self):
        self.label_20.setText(datetime.datetime.now().strftime("%d %b %Y %H : %M : %S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TY_05_SPEC_8_Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
